# This file is generated by device/Infinix/X6812/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files
#PRODUCT_PACKAGES += \
#    MTKLogger #    YGPS

# Proprietary dependencies go here

$(call inherit-product, vendor/Infinix/X6812/X6812-vendor-blobs.mk)
