
# This file is generated by device/Infinix/X6812/setup-makefiles.sh

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Infinix/X6812/bin,system/bin)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Infinix/X6812/etc,system/etc)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Infinix/X6812/lib,system/lib)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Infinix/X6812/lib64,system/lib64)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Infinix/X6812/usr,system/usr)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Infinix/X6812/vendor/bin,system/vendor/bin)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Infinix/X6812/vendor/etc,system/vendor/etc)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Infinix/X6812/vendor/firmware,system/vendor/firmware)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Infinix/X6812/vendor/lib,system/vendor/lib)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Infinix/X6812/vendor/lib64,system/vendor/lib64)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Infinix/X6812/vendor/thh,system/vendor/thh)
